# Generated by Django 3.2.7 on 2022-01-29 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDb',
            fields=[
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
