# Generated by Django 3.2.7 on 2022-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
